# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "ruff"
      - dependency-name: "ty"
      - dependency-name: "pre-commit"
      - dependency-name: "pytest"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "python"
      - dependency-name: "ghcr.io/astral-sh/uv"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "typer"
      - dependency-name: "rich"
      - dependency-name: "questionary"
      - dependency-name: "pydantic"
      - dependency-name: "cryptography"
      - dependency-name: "beautifulsoup4"
      - dependency-name: "html2text"
