changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes 🛠
      labels: ["type: breaking change"]
    - title: New features & enhancements ✨
      labels: ["type: feat", "type: enhancement"]
    - title: Bug Fixes 🐛
      labels: ["type: fix"]
    - title: Documentation 📖
      labels: ["service: docs"]
