default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v4.2.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.12.3'
    hooks:
      - id: ruff
        args: ["--fix", "--config", "./pyproject.toml"]
      - id: ruff-format
        args: ["--config", "./pyproject.toml"]
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check .
        language: system
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        args: ["./pyproject.toml"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: '0.7.20'
    hooks:
      - id: uv-lock
        args: ["--locked"]
