name: 🐛 Bug report
description: Create a report to help us improve the project
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        #### Before reporting a bug, please check that the issue hasn't already been addressed in [the existing and past issues](https://github.com/relaycli/relay/issues?q=is%3Aissue).
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of what the bug is.

        Please explain the result you observed and the behavior you were expecting.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code snippet to reproduce the bug
      description: |
        Minimal code snippet to reproduce the problem.

        Please wrap your code snippet with ```` ```triple quotes blocks``` ```` for readability.
      placeholder: |
        ```python
        Minimal code snippet to reproduce the problem
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console output
      description: |
        The error message you received running the code snippet, with the full traceback.

        Please wrap your error message with ```` ```triple quotes blocks``` ```` for readability.
      placeholder: |
        ```
        The error message you got, with the full traceback.
        ```
    validations:
      required: true
  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture are you using? (see `uname -orsm`)
      placeholder: e.g., macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of relaycli are you using? (see `relay version`)
      placeholder: e.g., relay 0.0.1
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: What version of Python are you using? (see `python --version`)
      placeholder: e.g., Python 3.11.10
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Being able to reproduce the behaviour is key to resolving bugs. Share a few information about your setup:
      placeholder: |
        - From source: Y/N
        - Commit hash:
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for helping us improve the library!
